### ISSUE TITLE
Jcenter artifact?

### ISSUE THREAD

**Issue by holgerbrandl** [redundent/kotlin-xml-builder#1]
Would it be possible to deploy it to jcenter as well? This would remove the necessity to add another  repo to my gradle file.

**Comment by redundent** [comment]
Sure. I just requested it to be included in jcenter. Will comment here when I get confirmation.

**Comment by holgerbrandl** [comment]
Awesome thanks!

**Comment by redundent** [comment]
Got approval this morning. Should be all set now. Let me know.

**Comment by holgerbrandl** [comment]
I'd love but could not find it via maven central (which is link to jcenter).  See yourself
http://mvnrepository.com/search?q=kotlin-xml-builder

Maybe you could also update the project-readme to refer to the jcenter artifact instead?

**Comment by redundent** [comment]
I believe it's the other way around (I could be wrong though). Everything in maven central will be in jcenter but not everything in jcenter will be in maven central.

I updated the readme to reference the jcenter repo instead of the custom one I had before.

**Comment by holgerbrandl** [comment]
No you're right about jcenter vs mc.

I've tried it and it works really well. Thanks a lot.
