### ISSUE TITLE
[Request] Support for rendering XML comments within generated XML

### ISSUE THREAD

**Issue by ejektaflex** [redundent/kotlin-xml-builder#20]
Currently, I don't see a way of adding comments via the DSL, and it seems quite hard to do because nodes need a name, and comments are inherently unnamed (Unless you could their contained text). Adding support for comments in generated XML would be greatly appreciated!

**Comment by ejektaflex** [comment]
For reference, I am using this:

```kotlin
package util

import org.redundent.kotlin.xml.Node

class XmlComment(text: String): Node(text) {
    override fun render(builder: StringBuilder, indent: String, prettyFormat: Boolean) {
        builder.append("<!-- $nodeName -->")
    }
}
```

You can adapt this or do something similar if you'd like!

**Comment by redundent** [comment]
Thanks @ejektaflex 
This has been added in version 1.5.1 which is available now
