### ISSUE TITLE
prolog hardcoded to 1.0, text is escaped to 1.1

### ISSUE THREAD

**Issue by ZR8C** [redundent/kotlin-xml-builder#22]
Text is encoded to the 1.1 schema of xml here:
https://github.com/redundent/kotlin-xml-builder/blob/fae1b2007b68df1e27f2b0f60b7273ab41fa1eed/kotlin-xml-builder/src/main/kotlin/org/redundent/kotlin/xml/TextElement.kt#L20

But the prolog string is hardcoded to 1.0:
https://github.com/redundent/kotlin-xml-builder/blob/fae1b2007b68df1e27f2b0f60b7273ab41fa1eed/kotlin-xml-builder/src/main/kotlin/org/redundent/kotlin/xml/Node.kt#L167

Ideally default to one or the other, and allow it to be specified.

**Comment by redundent** [comment]
Hi @ZR8C ,
Thanks for reporting this. I just published version 1.5.2 that has this fixed. You can now specify the version and the text escaping respects it.
