### ISSUE TITLE
XSL processing instruction

### ISSUE THREAD

**Issue by rjaros** [redundent/kotlin-xml-builder#28]
Is it possible to add processing instruction before the root element to generate XML like below?
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<document>
...
</document>
```

**Comment by redundent** [comment]
Hi @rjaros 
Currently no, that isn't possible.

I can see about adding it though.

**Comment by redundent** [comment]
HI @rjaros 
This has been published. You can find info on the readme. The updated version is 1.5.4

**Comment by rjaros** [comment]
It's working fine. Thx!
