### ISSUE TITLE
Minor readme changes proposals

### ISSUE THREAD

**Issue by mvysny** [redundent/kotlin-xml-builder#30]
Good day, I've found this library after wasting a day figuring out magic combination of annotations and configuration parameters for Jackson-XML. Thank you, and bless you!

I'd like to have a couple of suggestions:

1. Would it be possible to remove the kotlin-reflect dependency? It is quite huge (2,7mb) and can save a lot of space in the resulting binary (especially useful when running on Android)
2. README.md: Could you please format the dependencies{} block so that I can paste it to build.gradle.kts?

```
dependencies {
    compile("org.redundent:kotlin-xml-builder:[VERSION]")
}
```

3. README.md: Could you add example for Maven?

```
    <repositories>
        <repository>
             <id>jcenter</id>
             <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>

<dependencies>
        <dependency>
            <groupId>org.redundent</groupId>
            <artifactId>kotlin-xml-builder</artifactId>
            <version>[VERSION]</version>
        </dependency>
</dependencies>
```

4. Could you please publish the library on Maven repo? You will need to change the group id to com.github.redundent.kotlin-xml-builder and register at Maven JIRA as OSSRH, but no keys/signing is needed since Bintray will do that for you.

5. (A bit of a personal question): I've autored a kind of a sister-project for yours: https://gitlab.com/mvysny/konsume-xml - it reads XML rather than creates XMLs. Would you consider linking to my project from your README.md please? I've already linked to yours :)

Thank you again :+1:

**Comment by redundent** [comment]
Hi @mvysny 

1. Yes, I think I can do that. Reflection is used in one part of the project to control element order using the @XmlType attribute but I doubt many people use that. I can add a check if the reflect module is present before using reflection.

2. I will update that.

3. Will also update that.

4. I'll look into including this in maven central.

5. This project can actually read xml as well, although admittedly, it's not the best at it. Your project looks much more full featured so yes, I will add a link to it.
Thanks for the shout out in your project!

**Comment by redundent** [comment]
Hi @mvysny 
This should all be done now. All the requested changes have been made and version 1.6.0 was published to maven central.

**Comment by mvysny** [comment]
Thank you very much, awesome job :+1:
