### ISSUE TITLE
Kotlin Runtime bundled warning

### ISSUE THREAD

**Issue by JamesMcMahon** [redundent/kotlin-xml-builder#34]
I'm getting the following warning when I add this project as a dependency,

> w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /Users/james/.gradle/caches/modules-2/files-2.1/org.redundent/kotlin-xml-dsl-generator/1.6.0/de9bbf49abf21cc070a1a8bcd155bdc19776b5f6/kotlin-xml-dsl-generator-1.6.0.jar: Library has Kotlin runtime bundled into it

This then goes on to break the compilation of my project. I am guessing this is due to two conflicting Kotlin versions at play. My project is on Kotlin `1.3.72`.

**Comment by redundent** [comment]
Hi James,
The DSL Generator jar is meant to be a standalone executable jar to generate code based on an XSD. You shouldn't need to include it as a compile time dependency. The jar is actually a fat jar with a bunch of other dependencies you probably don't want.

Are you just trying to use the xml builder library or are you actually trying to generate some DSL code from an XSD?

**Comment by JamesMcMahon** [comment]
Oh jeez, I must have grabbed the wrong dependency from Maven Central and then had detail blindness when I looked over this repo's README.

I just want to use the library. I corrected the dependency and it fixed the issue above.
