### ISSUE TITLE
Feature request: Implement equals() and hashcode() in classes that implement Element

### ISSUE THREAD

**Issue by cbartolome** [redundent/kotlin-xml-builder#37]
Would it be possible for the classes that implement `Element` to include implementations for `equals()` and `hashCode()`? I ran into an issue where a unit test kept producing false negatives because identically constructed `Node` instances weren't registering as equal. Thanks!

**Comment by redundent** [comment]
Hi @cbartolome 
Can you explain your use case a bit more?
I can see some instances where 2 different nodes with the same content generating the same hashcode could potentially cause issues.

**Comment by cbartolome** [comment]
Sure thing. I'm trying to make a unit test that calls `assertEquals()` and passes a `Node` as the `expected` value and the result of the function I'm testing as the `actual` value. Since `Node` doesn't implement `equals()`, the assertion always fails.

**Comment by redundent** [comment]
I'm hesitant to override equals and hashCode because of potential side effects, like adding nodes to a set could lose nodes.
Would a different method like `isEqual(other: Element?): Boolean` be sufficient for you? Then you could use `assertTrue(expected.isEqual(actual))`

**Comment by cbartolome** [comment]
I mean, if somebody is inserting objects that don't implement `equals()` and `hashCode()` into a set, they kind of deserve what they get. I think I'll rework my tests to go in a different direction.

Thanks!

**Comment by cbartolome** [comment]
This is proving to be harder than I thought, as I can't easily use `assertEquals` at all on any object that has a `Node` in it.

**Comment by redundent** [comment]
I'll take a look at adding something for this a bit later today or tomorrow

**Comment by redundent** [comment]
@redundent This is done. I ended up just overriding equals and hashCode like you originally suggested. It seemed easier and you had a good point about hashCodes and Sets.

I'll publish the new version shortly

**Comment by cbartolome** [comment]
Awesome, thanks so much!

**Comment by redundent** [comment]
Just published this to maven central as version 1.7. It might take some time to show up.
Let me know if you have an issues with the implementation.
