### ISSUE TITLE
Node with element as empty string, does not care about useSelfClosingTags

### ISSUE THREAD

**Issue by d-wojciechowski** [redundent/kotlin-xml-builder#40]
Hello.

Firstly, this is a very nice library!
Secondly, I found a small bug.

When XML object is created, and as node body is given an empty string, and option **useSelfClosingTags** is used, the output is still with a closing tag.
```
            "csvparent" {
                    -parent // content is empty string
            }
// output is <csvparent></csvparent>
```

What I would expect is to have a self-closing tag

As a workaround following solution is applied:
```
            "csvparent" {
                if(parent.isNotBlank()){
                    -parent
                }
            }
```

**Comment by redundent** [comment]
Hey @d-wojciechowski 
1. Thanks!
2. I'll take a look tomorrow. Seems like a tiny fix so shouldn't be an issue

**Comment by redundent** [comment]
@d-wojciechowski 
This is fixed and published. Version 1.7.2 is available
