### ISSUE TITLE
Bintray is closing

### ISSUE THREAD

**Issue by tadfisher** [redundent/kotlin-xml-builder#42]
Bintray and JCenter are closing: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

The suggested repository to use is Maven Central. Documentation for applying is here: https://central.sonatype.org/pages/producers.html

If you need help navigating the process, I'm happy to help. I do use this tool regularly and it'd be a shame to lose access to it because of JFrog's decision.

**Comment by redundent** [comment]
Hey @tadfisher,
Thanks for the reminder. This project has been available in Maven Central for some time now. I just clearly never updated the documentation. I have just done that.
