### ISSUE TITLE
make private fun parse(document: Document): Node  public

### ISSUE THREAD

**Issue by rkklai** [redundent/kotlin-xml-builder#43]
Hello, can you please make the private fun parse(document: Document) public? I have a Document that's created by JAXB and wanted to parse it directly? Now I need to serialize JAXB to string and then the parse will parse the string to Document and then process it. Also, the parse function creates a new document builder factory and a new document builder every time which is very expensive. So if the parse(Document) is made public, I can just create one copy of document builder and reuse it. Thanks!

**Comment by redundent** [comment]
Hi @rkklai 
This is done and published. It should be available in Maven Central soon

**Comment by rkklai** [comment]
Thanks a lot @redundent!
