### ISSUE TITLE
[Question] How can I add a `DOCTYPE` element?

### ISSUE THREAD

**Issue by anskotid** [redundent/kotlin-xml-builder#47]
I need to do something like:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DataSet SYSTEM "example.dtd">
<DataSet>
   ...
</DataSet>
```

I tried many different approaches but none worked.

Is there a way to achieve this?

**Comment by redundent** [comment]
I don't think there is a way to do this right now. I can look into adding it.

**Comment by anskotid** [comment]
> @anskotid Version 1.7.4 has been published that allows for this. Check the README for an example

Wow, you're a gem, thank you so much!
