### ISSUE TITLE
Suggestion: create addNodes method

### ISSUE THREAD

**Issue by csmile2** [redundent/kotlin-xml-builder#59]
### Suggestion
A function to add multiple nodes at a time would be useful.
`addNodes(parentNode: Node, nodes: List<Node>)` in addition to singular (existing) `addNode(node: Node)`.

Thanks

**Comment by redundent** [comment]
Hey @csmile2,
Sorry for the delay in responding. I like the idea. I'll get that added in the next couple of days.

**Comment by redundent** [comment]
Took me longer than I'd hoped but version 1.9.1 is deployed. It includes new `addElements` methods. I renamed the existing `addNode` method to `addElement` since that's actually what it's doing.

**Comment by csmile2** [comment]
Cool, looks like it's working as expected. Much appreciated!
