### ISSUE TITLE
xml encoding prelude ?

### ISSUE THREAD

**Issue by luistrigueiros** [redundent/kotlin-xml-builder#6]
How can I get the initial xml encoding prelude to be outputted, something like:

<?xml version="1.0" encoding="UTF-8"?>

Thank you, 
Luis Oscar

**Comment by redundent** [comment]
Hey Luis,
Sorry for the delay.
There isn't a way to include that right now. I'll try to take a look at adding it tomorrow. Should be pretty easy.

**Comment by luistrigueiros** [comment]
Thank you, I love the code you have by the way.

**Comment by redundent** [comment]
Thanks!

I just published version 1.4.2 which has the ability to specify the encoding.
