### ISSUE TITLE
Option to disable indentation

### ISSUE THREAD

**Issue by vincentburesi-es** [redundent/kotlin-xml-builder#61]
It would be nice to have an option to easily disable all indentation and unnecessary spaces to get a "minified" output.

Currently setting pretty to false in the toString function arguments doesn't seem to do that, which is what I would expect it to do.

**Comment by redundent** [comment]
Hi @vincentburesi-es 
Can you provide a sample of your code where you are seeing indentation when `pretty` is set to false?
When pretty is false, all indentation and new lines should be removed.

**Comment by Zordid** [comment]
I can ensure that with pretty print off, there is no indentation whatsoever... So I think there is something wrong in the setup used.

**Comment by redundent** [comment]
No worries. Glad it's working as expected.
