### ISSUE TITLE
Pretty formatting with generated DSL

### ISSUE THREAD

**Issue by VieuxChameau** [redundent/kotlin-xml-builder#7]
Hello,

I have used the project kotlin-xml-dsl-generator to generate the DSL from some XSDs.

I wanted my xml generated to be not formatted. I did not see a solution apart of modifying the generated DSL to make the prettyFormat to false.

I would like to avoid to modify the generated DSL so I could make it part of the generated source, like you would do for JAXB plugin.

I see two solutions:

- add an option to the generator regarding the pretty format
- add a new function to get the xml (instead of the toString)  maybe on the Element interface that would take  the pretty format option, at the time we want the XML representation of the node rather than the construction of it. Maybe taking the includeXmlProlog param as well?

The second solution seems to be the best but probably requires more changes in the code.

Thank you for the tool.

**Comment by redundent** [comment]
This has been published as version 1.4.3.
